
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.minyazi.test.webservice.client1;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-14T17:38:19.976+08:00
 * Generated source version: 3.0.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "IpAddressSearchWebService",
                      portName = "IpAddressSearchWebServiceHttpPost",
                      targetNamespace = "http://WebXml.com.cn/",
                      wsdlLocation = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl",
                      endpointInterface = "com.minyazi.test.webservice.client1.IpAddressSearchWebServiceHttpPost")
                      
public class IpAddressSearchWebServiceHttpPostImpl implements IpAddressSearchWebServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(IpAddressSearchWebServiceHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client1.IpAddressSearchWebServiceHttpPost#getCountryCityByIp(java.lang.String theIpAddress)*
     */
    public com.minyazi.test.webservice.client1.ArrayOfString getCountryCityByIp(java.lang.String theIpAddress) { 
        LOG.info("Executing operation getCountryCityByIp");
        System.out.println(theIpAddress);
        try {
            com.minyazi.test.webservice.client1.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client1.IpAddressSearchWebServiceHttpPost#getVersionTime()*
     */
    public java.lang.String getVersionTime() { 
        LOG.info("Executing operation getVersionTime");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client1.IpAddressSearchWebServiceHttpPost#getGeoIPContext()*
     */
    public com.minyazi.test.webservice.client1.ArrayOfString getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            com.minyazi.test.webservice.client1.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
