
package com.minyazi.j2ee.test.webservice.client3;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-16T17:04:34.597+08:00
 * Generated source version: 3.0.15
 * 
 */
public final class HelloWorldWebService_HelloWorldWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webservice.service.minyazi.com/", "HelloWorldWebServiceImplService");

    private HelloWorldWebService_HelloWorldWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldWebServiceImplService ss = new HelloWorldWebServiceImplService(wsdlURL, SERVICE_NAME);
        HelloWorldWebService port = ss.getHelloWorldWebServiceImplPort();  
        
        {
        System.out.println("Invoking sayHelloWorld...");
        java.lang.String _sayHelloWorld_arg0 = "";
        java.lang.String _sayHelloWorld__return = port.sayHelloWorld(_sayHelloWorld_arg0);
        System.out.println("sayHelloWorld.result=" + _sayHelloWorld__return);


        }

        System.exit(0);
    }

}
