package com.minyazi.j2ee.test.webservice.client3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-16T17:04:34.659+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebServiceClient(name = "HelloWorldWebServiceImplService", 
                  wsdlLocation = "http://localhost:8080/minyazi-web/ws/helloWorldWS?wsdl",
                  targetNamespace = "http://impl.webservice.service.minyazi.com/") 
public class HelloWorldWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.service.minyazi.com/", "HelloWorldWebServiceImplService");
    public final static QName HelloWorldWebServiceImplPort = new QName("http://impl.webservice.service.minyazi.com/", "HelloWorldWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/minyazi-web/ws/helloWorldWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/minyazi-web/ws/helloWorldWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebService getHelloWorldWebServiceImplPort() {
        return super.getPort(HelloWorldWebServiceImplPort, HelloWorldWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldWebService
     */
    @WebEndpoint(name = "HelloWorldWebServiceImplPort")
    public HelloWorldWebService getHelloWorldWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldWebServiceImplPort, HelloWorldWebService.class, features);
    }

}
