
package com.minyazi.test.webservice.client2;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-14T17:20:11.014+08:00
 * Generated source version: 3.0.15
 * 
 */
 
public class DataTypeWebService_DataTypeWebServiceImplPort_Server{

    protected DataTypeWebService_DataTypeWebServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new DataTypeWebServiceImplPortImpl();
        String address = "http://localhost:9000/ws/DataTypeWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new DataTypeWebService_DataTypeWebServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
