
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.minyazi.test.webservice.client2;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-14T17:20:10.983+08:00
 * Generated source version: 3.0.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "DataTypeWebServiceImplService",
                      portName = "DataTypeWebServiceImplPort",
                      targetNamespace = "http://webservice.test.minyazi.com/",
                      wsdlLocation = "http://localhost:9000/ws/DataTypeWS?wsdl",
                      endpointInterface = "com.minyazi.test.webservice.client2.DataTypeWebService")
                      
public class DataTypeWebServiceImplPortImpl implements DataTypeWebService {

    private static final Logger LOG = Logger.getLogger(DataTypeWebServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client2.DataTypeWebService#getUserById(java.lang.Integer arg0)*
     */
    public com.minyazi.test.webservice.client2.User getUserById(java.lang.Integer arg0) { 
        LOG.info("Executing operation getUserById");
        System.out.println(arg0);
        try {
            com.minyazi.test.webservice.client2.User _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client2.DataTypeWebService#isExist(com.minyazi.test.webservice.client2.User arg0)*
     */
    public boolean isExist(com.minyazi.test.webservice.client2.User arg0) { 
        LOG.info("Executing operation isExist");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client2.DataTypeWebService#getUserName(java.lang.Integer arg0)*
     */
    public java.lang.String getUserName(java.lang.Integer arg0) { 
        LOG.info("Executing operation getUserName");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client2.DataTypeWebService#getUsers()*
     */
    public com.minyazi.test.webservice.client2.HashMap getUsers() { 
        LOG.info("Executing operation getUsers");
        try {
            com.minyazi.test.webservice.client2.HashMap _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.client2.DataTypeWebService#getUsersByName(java.lang.String arg0)*
     */
    public java.util.List<com.minyazi.test.webservice.client2.User> getUsersByName(java.lang.String arg0) { 
        LOG.info("Executing operation getUsersByName");
        System.out.println(arg0);
        try {
            java.util.List<com.minyazi.test.webservice.client2.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
