
package com.minyazi.test.webservice.client1;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-14T17:38:20.021+08:00
 * Generated source version: 3.0.15
 * 
 */
 
public class IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Server{

    protected IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IpAddressSearchWebServiceSoapImpl();
        String address = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IpAddressSearchWebServiceSoap_IpAddressSearchWebServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
