
package com.minyazi.test.webservice.client3;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-16T17:04:34.656+08:00
 * Generated source version: 3.0.15
 * 
 */
 
public class HelloWorldWebService_HelloWorldWebServiceImplPort_Server{

    protected HelloWorldWebService_HelloWorldWebServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloWorldWebServiceImplPortImpl();
        String address = "http://localhost:8080/minyazi-web/ws/helloWorldWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloWorldWebService_HelloWorldWebServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
