package com.minyazi.test.webservice.client3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-16T17:04:34.650+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebService(targetNamespace = "http://webservice.service.minyazi.com/", name = "HelloWorldWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webservice.service.minyazi.com/", className = "com.minyazi.test.webservice.client3.SayHelloWorld")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webservice.service.minyazi.com/", className = "com.minyazi.test.webservice.client3.SayHelloWorldResponse")
    public java.lang.String sayHelloWorld(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
