
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.minyazi.test.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-13T15:06:15.843+08:00
 * Generated source version: 3.0.15
 * 
 */

@javax.jws.WebService(
                      serviceName = "IpAddressSearchWebService",
                      portName = "IpAddressSearchWebServiceSoap",
                      targetNamespace = "http://WebXml.com.cn/",
                      wsdlLocation = "http://www.webxml.com.cn/WebServices/IpAddressSearchWebService.asmx?wsdl",
                      endpointInterface = "com.minyazi.test.webservice.IpAddressSearchWebServiceSoap")
                      
public class IpAddressSearchWebServiceSoapImpl implements IpAddressSearchWebServiceSoap {

    private static final Logger LOG = Logger.getLogger(IpAddressSearchWebServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.IpAddressSearchWebServiceSoap#getCountryCityByIp(java.lang.String theIpAddress)*
     */
    public com.minyazi.test.webservice.ArrayOfString getCountryCityByIp(java.lang.String theIpAddress) { 
        LOG.info("Executing operation getCountryCityByIp");
        System.out.println(theIpAddress);
        try {
            com.minyazi.test.webservice.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.IpAddressSearchWebServiceSoap#getVersionTime()*
     */
    public java.lang.String getVersionTime() { 
        LOG.info("Executing operation getVersionTime");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.minyazi.test.webservice.IpAddressSearchWebServiceSoap#getGeoIPContext()*
     */
    public com.minyazi.test.webservice.ArrayOfString getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            com.minyazi.test.webservice.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
