package com.minyazi.j2ee.test.webservice.client2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.15
 * 2017-11-16T11:21:35.301+08:00
 * Generated source version: 3.0.15
 * 
 */
@WebService(targetNamespace = "http://webservice.test.minyazi.com/", name = "DataTypeWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DataTypeWebService {

    @RequestWrapper(localName = "addUsers2", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.AddUsers2")
    @WebMethod
    @ResponseWrapper(localName = "addUsers2Response", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.AddUsers2Response")
    public void addUsers2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.minyazi.j2ee.test.webservice.client2.MapConvertor arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUserName")
    @WebMethod
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUserNameResponse")
    public java.lang.String getUserName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUsers")
    @WebMethod
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUsersResponse")
    public com.minyazi.j2ee.test.webservice.client2.MapConvertor getUsers();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUserById")
    @WebMethod
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUserByIdResponse")
    public com.minyazi.j2ee.test.webservice.client2.User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isExist", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.IsExist")
    @WebMethod
    @ResponseWrapper(localName = "isExistResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.IsExistResponse")
    public boolean isExist(
        @WebParam(name = "arg0", targetNamespace = "")
        com.minyazi.j2ee.test.webservice.client2.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByName", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUsersByName")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByNameResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.GetUsersByNameResponse")
    public java.util.List<com.minyazi.j2ee.test.webservice.client2.User> getUsersByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @RequestWrapper(localName = "addUsers", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.AddUsers")
    @WebMethod
    @ResponseWrapper(localName = "addUsersResponse", targetNamespace = "http://webservice.test.minyazi.com/", className = "com.minyazi.test.webservice.client2.AddUsersResponse")
    public void addUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.minyazi.j2ee.test.webservice.client2.User> arg0
    );
}
